### ISSUE TITLE
[Phoenix] Making OSM navigation ready

### ISSUE THREAD

**Issue by manuelab-telenav** [TelenavMapping/mapping-projects#24]
## Description
This project is designed to improve the quality of OSM by adding various map features used for navigation, in Phoenix, Arizona.
![ph](https://user-images.githubusercontent.com/24428741/30280449-6c6ea550-9718-11e7-9501-d627802ae036.png)
## What we map
In the following period we will focus on adding:
* road geometry
* road name
* one ways
* turn restrictions
* gates
* speed limit
* traffic lights
* lanes and turn lanes
* signposts
* HOV lanes
* toll roads

### Government data:
* Tiger roads

### Satellite imagery:
* Bing
* Digital Globe
* NAIP 2015 

### Street-level imagery
* OpenStreetCam
* Mapillary

### Others:
* ImproveOSM plugin

## Who will be involved
[Telenav mapping team](https://github.com/TelenavMapping/mapping-projects/wiki/Team)

**Comment by andreis-telenav** [comment]
The role of our project was to improve the quality of the OSM features used for navigation, in Phoenix Arizona.

Starting from September till now, the whole project workflow was realized in 3 main steps:

**Step 1.** Research and get in touch with local community (research on local open source data, keep in touch with local OMS users, official traffic signs and driving rules, research on HOV and toll roads, roads under construction, other specific road features of Arizona State).

**Step 2.** Build-up process:
1.	Road geometry, Road Name, One Way, Gates and Other Geometric Feature (turning circles, turning loops, etc.)
2.	Signpost
3.	Turn Restrictions and Traffic Lights
4.	Lane and Turn Lane Info, including HOV Lanes and Toll Roads
5.	Speed Limit Editing.

**Step 3.** Quality Assurance (QA for every feature edited by our team in OSM, some road name special issues, repairing broken relations, final edits and corrections based on Improve OSM plug-in, Osmose and Keep Right errors, tile by tile verification).

**The first step** was a very important one because the team had to get in touch with the local community and mapping rules. Also, a research was made for finding other open source and free of charged data beside the already well-known sources used by OSM users (TIGER Roads, Bing, Digital Globe, Open Street Cam, Mapillary). The under-construction roads found in this step were permanently monitored in order to be edited later.

**The second step** was the most time consuming and it included the editing and reviewing of all the most important navigable OSM features, starting from motorway, trunk, primary, secondary, tertiary, residential and service ways. The whole editing process last for about 3 moths and the workflow was mainly based on tile by tile method but, we also edited based on way category or REF. During this period, we helped the community to increase the OSM quality as you can see below:

![1](https://user-images.githubusercontent.com/24649912/34870083-b1f03c22-f791-11e7-9bfb-a2de86b06f6e.jpg)

![2](https://user-images.githubusercontent.com/24649912/34870140-e6f3909a-f791-11e7-88e9-682c0c9bb36d.jpg)
![3](https://user-images.githubusercontent.com/24649912/34870144-e9fce35e-f791-11e7-85ac-e9136fde474e.jpg)
![4](https://user-images.githubusercontent.com/24649912/34870166-fd959942-f791-11e7-8fbb-b55f243b6b5d.jpg)
![5](https://user-images.githubusercontent.com/24649912/34870168-00f65932-f792-11e7-97ed-8bfacb35eeb3.jpg)

**The third step** was the last but not the less important. Because we wanted to have a good quality features in OSM, we had to make a closure check on our edits, already made in the build-up process and where it was necessarly, to feel the gaps. So, we used different QA procedures, script, other plug-ins, error identifiers and even tile by tile verification. Doing that, we had an important overview of our whole edits, especially of our wrong ones.  In this step, we resolved also a name tag issue we’d came across during step 2, which is detailed by my colleagues, in the following link https://github.com/TelenavMapping/mapping-projects/issues/35. Step 3 represents for Telenav team also a certainty of good quality editing.

In the moment when we needed a double check for our work, the community was a good help, giving us important feedbacks. For the next months, we’ll surely keep in touch continuously with the local OSM users, looking forward for their feedback in order to keep up a good maintenance work.

In the heatmap below you can see an evolution of our edits during those 4 moths, on Phoenix, Arizona.
![phoenix](https://user-images.githubusercontent.com/24649912/34870244-31e71df6-f792-11e7-8fe2-cef16f119cd5.gif)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#5
