### ISSUE TITLE
When renaming streets, addresess not changed at the same time

### ISSUE THREAD

**Issue by martijnv-telenav** [TelenavMapping/mapping-projects#34]
_From @matthewdarwin on October 11, 2017 14:24_

I see a lot of changes where someone with a _telenav OSM address is renaming a street, but they are not also renaming the addresses along the street at the same time.

I am focused on Ottawa Canada and surrounding area.

These errors show up in the OSM inspector https://tools.geofabrik.de/osmi/  Addresses => Nodes With Addresses => Street Not Found

I have been adding comments to the changes, but there quite a lot of them. 

_Copied from original issue: Telenav/mapping#3_

**Comment by martijnv-telenav** [comment]
_From @mvexel on October 11, 2017 17:36_

@matthewdarwin thanks for raising this, we will come up with a plan to address this, and my apologies.

Let me talk to the team and get back to you soonest.

**Comment by martijnv-telenav** [comment]
_From @mvexel on October 11, 2017 17:39_

<img width="845" alt="screenshot 2017-10-11 11 38 45" src="https://user-images.githubusercontent.com/120452/31457031-c78d791c-ae78-11e7-86ee-070201f9cd6c.png">

Is [this](https://tools.geofabrik.de/osmi/?view=addresses&lon=-75.68944&lat=45.40943&zoom=11&overlays=no_addr_street,street_not_found,place_not_found,misformatted_housenumber) the view you are referring to, @matthewdarwin ?

**Comment by martijnv-telenav** [comment]
_From @mvexel on October 11, 2017 17:57_

Also, our official mapping repository is at https://github.com/TelenavMapping/mapping-projects . I will move this issue there, close the issue here and delete the old repository.

**Comment by mvexel** [comment]
Hi all, 

Frederik Ramm (who maintains OSM Inspector) was kind enough to share a dump of all the current 'Street not found' nodes in Canada. See attached.

There are a lot of these nodes. Not all are caused by us, but a lot are. We are looking for a smart way to update these orphaned nodes and bring them in line with the updated street names. If we come up with a cleanup method, we will share this and ask for more input. 

[street_not_found.zip](https://github.com/TelenavMapping/mapping-projects/files/1432446/street_not_found.zip)

**Comment by hoream-telenav** [comment]
This issue was moved to TelenavMapping/US-mapping-projects#9
